rn_quiz/homesite/homesite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from quiz import forms, views
from datetime import datetime

urlpatterns = [
    path('', include('quiz.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/',
         LoginView.as_view
         (
             template_name='login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('quiz/', include('quiz.urls')),
]

rn_quiz/homesite/quiz/urls.py
from django.urls import path,include
from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('startquiz/', views.start_quiz, name='startquiz'),
    path('signup/', views.signup,name='signup'),
    path('startquiz/<int:page_id>', views.startquizmonitor, name='startquiz'),
]

rn_quiz/homesite/quiz/models.py
import datetime
from django.db import models
from django.utils import timezone

class UsersAnswers(models.Model):
    question_id = models.IntegerField()
    account_id = models.IntegerField()
    created_date= models.DateTimeField()

    def __str__(self):
        return self.question_text

class UserAnswerList(models.Model):
    UsersAnswers = models.ForeignKey(UsersAnswers, on_delete=models.CASCADE)
    answer_id = models.IntegerField()
    created_date= models.DateTimeField()
    
    def __str__(self):
        return self.choice_text

rn_quiz/homesite/quiz/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
                                   

rn_quiz/homesite/quiz/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.template import loader 
from django.http import Http404
from quiz.blogic.questions_reader import reader
from django.contrib.auth.forms import UserCreationForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.backends.db import SessionStore
from collections import Counter
import json
import functools


def signup(request):
    context = {}    
    if request.method=="POST":
        f_user_form = UserCreationForm(request.POST)
        if f_user_form.is_valid():
            f_user_form.save()
            return render(request, 'quiz/index.html', {})
    else:
        f_user_form= UserCreationForm()
        context = {
        'form': f_user_form,
        }
        return render(request, 'quiz/signup.html', context)

def index(request):
    latest_question_list = []
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'quiz/index.html', context)

def load_random_question():
    dict_from_file = reader.question_reader
    latest_question_list = dict_from_file.read_json_file() 
    questions = latest_question_list[0:25]
    return questions

@login_required
def start_quiz(request):
    questions = load_random_question()
    request.session['questions']  = questions
    request.session['users_answers'] ={}
    context = {
        'users_answers': None,
        'latest_question_list': [questions[0]],
        'next_question' : 1,
        'length_of_dataset': len(questions),
    }
    request.session['context'] =context
    return render(request, 'quiz/startquiz.html', context)

@login_required
def startquizmonitor(request,page_id):
    questions = request.session['questions']
    x = request.session['users_answers']
    if request.method=="POST":
        question_id = request.POST['question_id']       
        x.update(
             {
                 question_id : request.POST.getlist('q_answers')
             })
        request.session['users_answers'] = x 
    
    if page_id == len(questions):

        return render(request, 'quiz/results.html', 
                context={
                'users_answers': request.session['users_answers'],
                'latest_question_list': questions,
                'next_question' : 0,
                'length_of_dataset': len(questions),
                'score' : get_calulated_score(questions,request.session['users_answers'])
                }
        )

    context = {
        'users_answers': None,
        'latest_question_list': [questions[page_id]],
        'next_question' : page_id + 1,
        'length_of_dataset': len(questions),
    }
    return render(request, 'quiz/startquizmonitor.html', context)


def get_calulated_score(questions,uanswers):
        correct_answers=0
        quest_answer =None
        
        for uans,uans_value in uanswers.items():
            for quest in questions:
                if quest['qid'] == uans:
                    quest_answer = quest['content']['answers']
                    break
                
            #x.append((map(lambda x, y: x == y,quest_answer ,uans_value)))
            if Counter(quest_answer) == Counter(uans_value):
                correct_answers =correct_answers + 1

        return 0 if correct_answers<= 0 else (correct_answers/len(questions))*100    

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'quiz/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % request.POST['usrname'])

def vote_clear(request, question_id):
    return HttpResponse("You're voting the clear page on question %s." % request.POST['usrname'])

rn_quiz/homesite/quiz/templates/quiz/index.html
{% extends "base_site.html" %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        <h2>Your results </h2>
        <p>
            Contact the course administrator of this website to provide you with a login. Start you journey!
        </p>
        {% comment %} <p><a class="btn btn-default" href="https://djangobook.com/django-tutorials/">Learn more &raquo;</a></p> {% endcomment %}
    </div>
</div>

{% endblock %}

rn_quiz/homesite/quiz/templates/quiz/results.html
{% extends "base_site.html" %}
{% block content %}

<br>
<h1 class="display-5">Congratulations! Please review your results now</h1>
<p class="lead">
    Your score : <strong> {{score}} </strong>
</p>
<hr>
<br>

{% if latest_question_list %}
{% for latest_question in latest_question_list %}
    {% comment %} getting the data from a answer list that the user have created  {% endcomment %}
        {% comment %} {% for qid,answerid in users_answers.items %}
            {% if qid in latest_question.qid %}
                {% with useranswerid={{answerid}} %}
                        {{useranswerid}} = {{None}}
                        <p>{{useranswerid}}</p>
                {% endwith %}
            {{ break }}
            {% endif %}
        {% endfor %} {% endcomment %}
    

<input type="hidden" id="question_id" value={{latest_question.qid}} name="question_id">
<div class="card">
    <div class="card-header">
        <h5>Question : {{latest_question.qid}}</h5>
        <b>Referance from : {{latest_question.content.reference}} </b>  
    </div>
    <div class="card-body">
        <h5 class="card-title">{{latest_question.content.stem}}</h5>
        <p class="card-text">
            {% for option,optionvalue in latest_question.content.option.items %}
            {% if optionvalue %}
            <table>
                <tr>
                    <td>
                        {% for answers in latest_question.content.answers %}
                            {% if option in answers %}
                                    <label class="control control-checkbox">
                                        <input type="checkbox" value="{{ option }}" id="{{ option }}" name="q_answers"
                                            {{ option }} />
                                        <b class = "answercolor" >{{optionvalue}}</b>
                                        <div class="control_indicator"></div>
                                    </label>
                            {% else %}
                                <label class="control control-checkbox">
                                    <input type="checkbox" value="{{ option }}" id="{{ option }}" name="q_answers"
                                        {{ option }} />
                                    {{optionvalue}}
                                    <div class="control_indicator"></div>
                                </label>
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                </tr>
            </table>
            {% endif %}
            {% endfor %}

            <hr>
            <h5>Rationale</h5>
            <hr>
                </p>
                    {% for rationalkey,rationalvalue in latest_question.content.rationale.items %}
                        {% if rationalvalue %}
                        <p>
                            {{rationalkey}} - {{rationalvalue}}
                        </p>
                    {% endif %}
                {% endfor %}
                </p>

            <hr>
            <h5>Your Answers</h5>
            <hr>
                </p>
                    {% for qid,answerid in users_answers.items %}
                        {% if answerid %}
                            {% if qid == latest_question.qid %}  
                                {% for option,optionvalue in latest_question.content.option.items %}
                                    {% if option in answerid %}
                                        {% for answer in latest_question.content.answers %}
                                            {%for eans in answerid %}
                                                {% if answer in eans %}
                                                    <p>
                                                        <span class="glyphicon glyphicon-asterisk"></span>
                                                        <b class ="answercolor">{{option}} :  {{optionvalue}} </b>
                                                    </p>
                                                    {% else %}
                                                    <p>
                                                        <span class="glyphicon glyphicon-asterisk"></span>
                                                        <b class ="WrongAnswerColor">{{option}} :  {{optionvalue}} </b>
                                                    </p>
                                                {% endif %}
                                            {% endfor %}
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}            
                            {% endif %} 
                        {% endif %}
                    {% endfor %}
                </p>
    </div>
</div>
<br>
{% endfor %}
{% endif %}

It is {% now "jS F Y H:i" %}

{% endblock %}

{% block scripts %}
{% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>
<style>
    .answercolor{
        color: green;
    }
    .WrongAnswerColor{
        color: red;
    }
    .control {
        font-family: arial;
        display: block;
        position: relative;
        padding-left: 28px;
        margin-bottom: 15px;
        padding-top: 10px;
        cursor: pointer;
        font-size: 16px;
    }

    .control input {
        position: absolute;
        z-index: -1;
        opacity: 0;
    }

    .control_indicator {
        position: absolute;
        top: 10px;
        left: 0;
        height: 20px;
        width: 20px;
        background: #e6e6e6;
        border: 0px solid #000000;
    }

    .control-radio .control_indicator {
        border-radius: undefined%;
    }

    .control:hover input~.control_indicator,
    .control input:focus~.control_indicator {
        background: #cccccc;
    }

    .control input:checked~.control_indicator {
        background: #000000;
    }

    .control:hover input:not([disabled]):checked~.control_indicator,
    .control input:checked:focus~.control_indicator {
        background: #0e6647d;
    }

    .control input:disabled~.control_indicator {
        background: #e6e6e6;
        opacity: 0.6;
        pointer-events: none;
    }

    .control_indicator:after {
        box-sizing: unset;
        content: '';
        position: absolute;
        display: none;
    }

    .control input:checked~.control_indicator:after {
        display: block;
    }

    .control-checkbox .control_indicator:after {
        left: 8px;
        top: 4px;
        width: 3px;
        height: 8px;
        border: solid #ffffff;
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
    }


    .control-checkbox input:disabled~.control_indicator:after {
        border-color: #7b7b7b;
    }
</style>
</head>

{% endblock %}

rn_quiz/homesite/quiz/templates/quiz/signup.html
{% extends "base_site.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <h1>Sign Up</h1>
            <form action="." method="post" class="form-form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                    {{form|crispy}}  
                    <input type="submit" value="Log in" class="btn btn-default" />
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}

rn_quiz/homesite/quiz/templates/quiz/startquiz.html
{% extends "base_site.html" %}
{% block content %}
{% comment %} {{latest_question_list}} {% endcomment %}
<form action="./{{next_question}}"  method="post" >
{% csrf_token %}
{% comment %} 
    {% if latest_question_list.paginator.page_range <= latest_question_list.next_page_number %}
        {% with pageNumber=latest_question_list.next_page_number %}
        {% endwith %}
    {% else %}
        {% with pageNumber=latest_question_list.paginator.page_range %}
        {% endwith %} 
    {% endif %} 
{% endcomment %}

<br>
<h1 class="display-4">Questions in random order</h1>
<p class="lead">
    Please answer the questions and hit submit to evaluate and show rational
</p>
<hr>
<br>

{% if latest_question_list %}
{% for latest_question in latest_question_list %}
<input type="hidden" id="question_id" value={{latest_question.qid}} name="question_id">
<div class="card">
    <div class="card-header">
        <h4>Question : {{latest_question.qid}}</h4>
        <strong>Referance from : {{latest_question.content.reference}} </strong> 
    </div>
    <div class="card-body">
        <h5 class="card-title">{{latest_question.content.stem}}</h5>
        <p class="card-text">
            {% for option,optionvalue in latest_question.content.option.items %}
            {% if optionvalue %}
            <table>
                <tr>
                    <td>
                        <label class="control control-checkbox">
                            <input type="checkbox" value="{{ option }}" id="{{ option }}" name="q_answers"
                            {{ option }} />{{optionvalue}}
                            <div class="control_indicator"></div>
                        </label>
                    </td>
                    <td>
                    </td>
                </tr>
            </table>
            {% endif %}
            {% endfor %}
        </p>
    </div>
</div>
<br>
{% endfor %}

{% else %}
<p>No questions are available.</p>
{% endif %}
    <input type="submit" value="Submit" class="btn btn-default" />
</form>
{% endblock %}


{% block scripts %}
{% load staticfiles %}
<style>
    .control {
        font-family: arial;
        display: block;
        position: relative;
        padding-left: 28px;
        margin-bottom: 15px;
        padding-top: 10px;
        cursor: pointer;
        font-size: 16px;
    }

    .control input {
        position: absolute;
        z-index: -1;
        opacity: 0;
    }

    .control_indicator {
        position: absolute;
        top: 10px;
        left: 0;
        height: 20px;
        width: 20px;
        background: #e6e6e6;
        border: 0px solid #000000;
    }

    .control-radio .control_indicator {
        border-radius: undefined%;
    }

    .control:hover input~.control_indicator,
    .control input:focus~.control_indicator {
        background: #cccccc;
    }

    .control input:checked~.control_indicator {
        background: #000000;
    }

    .control:hover input:not([disabled]):checked~.control_indicator,
    .control input:checked:focus~.control_indicator {
        background: #0e6647d;
    }

    .control input:disabled~.control_indicator {
        background: #e6e6e6;
        opacity: 0.6;
        pointer-events: none;
    }

    .control_indicator:after {
        box-sizing: unset;
        content: '';
        position: absolute;
        display: none;
    }

    .control input:checked~.control_indicator:after {
        display: block;
    }

    .control-checkbox .control_indicator:after {
        left: 8px;
        top: 4px;
        width: 3px;
        height: 8px;
        border: solid #ffffff;
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
    }


    .control-checkbox input:disabled~.control_indicator:after {
        border-color: #7b7b7b;
    }
</style>
</head>

{% endblock %}

rn_quiz/homesite/quiz/templates/quiz/startquizmonitor.html
{% extends "base_site.html" %}
{% block content %}
<form action="./{{next_question}}"  method="post" >
{% csrf_token %}
{% comment %} 
    {% if latest_question_list.paginator.page_range <= latest_question_list.next_page_number %}
        {% with pageNumber=latest_question_list.next_page_number %}
        {% endwith %}
    {% else %}
        {% with pageNumber=latest_question_list.paginator.page_range %}
        {% endwith %} 
    {% endif %} 
{% endcomment %}

<br>
<h1 class="display-4">Questions in random order</h1>
<p class="lead">
    Please answer the questions and hit submit to evaluate and show rational
</p>
<hr>
<br>

{% if latest_question_list %}
{% for latest_question in latest_question_list %}
<input type="hidden" id="question_id" value={{latest_question.qid}} name="question_id">
<div class="card">
    <div class="card-header">
        <h4>Question : {{latest_question.qid}}</h4>
        <strong>Referance from : {{latest_question.content.reference}} </strong> 
    </div>
    <div class="card-body">
        <h5 class="card-title">{{latest_question.content.stem}}</h5>
        <p class="card-text">
            {% for option,optionvalue in latest_question.content.option.items %}
            {% if optionvalue %}
            <table>
                <tr>
                    <td>
                        <label class="control control-checkbox">
                            <input type="checkbox" value="{{ option }}" id="{{ option }}" name="q_answers"
                            {{ option }} />{{optionvalue}}
                            <div class="control_indicator"></div>
                        </label>
                    </td>
                    <td>
                    </td>
                </tr>
            </table>
            {% endif %}
            {% endfor %}
        </p>
    </div>
</div>
<br>
{% endfor %}


{% if latest_question_list.has_other_pages %}
<ul class="pagination">
    {% if latest_question_list.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ users.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in latest_question_list.paginator.page_range %}
        {% if latest_question_list.number == i %}
            <li class="active">
                <span>{{ i }} <span class="sr-only"></span>
                </span>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}
                </a>
            </li>
        {% endif %}
    {% endfor %}
    {% if latest_question_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ latest_question_list.next_page_number }}">&raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>



<input type="submit" value="Submit" class="btn btn-default" />
{% endif %}

{% else %}
<p>No questions are available.</p>
{% endif %}
<input type="submit" value="Submit" class="btn btn-default" />
</form>
{% endblock %}


{% block scripts %}
{% load staticfiles %}
<style>
    .control {
        font-family: arial;
        display: block;
        position: relative;
        padding-left: 28px;
        margin-bottom: 15px;
        padding-top: 10px;
        cursor: pointer;
        font-size: 16px;
    }

    .control input {
        position: absolute;
        z-index: -1;
        opacity: 0;
    }

    .control_indicator {
        position: absolute;
        top: 10px;
        left: 0;
        height: 20px;
        width: 20px;
        background: #e6e6e6;
        border: 0px solid #000000;
    }

    .control-radio .control_indicator {
        border-radius: undefined%;
    }

    .control:hover input~.control_indicator,
    .control input:focus~.control_indicator {
        background: #cccccc;
    }

    .control input:checked~.control_indicator {
        background: #000000;
    }

    .control:hover input:not([disabled]):checked~.control_indicator,
    .control input:checked:focus~.control_indicator {
        background: #0e6647d;
    }

    .control input:disabled~.control_indicator {
        background: #e6e6e6;
        opacity: 0.6;
        pointer-events: none;
    }

    .control_indicator:after {
        box-sizing: unset;
        content: '';
        position: absolute;
        display: none;
    }

    .control input:checked~.control_indicator:after {
        display: block;
    }

    .control-checkbox .control_indicator:after {
        left: 8px;
        top: 4px;
        width: 3px;
        height: 8px;
        border: solid #ffffff;
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
    }


    .control-checkbox input:disabled~.control_indicator:after {
        border-color: #7b7b7b;
    }
</style>
</head>

{% endblock %}

rn_quiz/homesite/templates/base_site.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz Master</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>

</head>

<body>
<div class="container">
<div class="navbar-header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Beyond Coaching!</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active"><a class="nav-link" href="{% url 'quiz:index' %}">Home<span
                                class="sr-only">(current)</span></a>
                    <li class="nav-item"><a class="nav-link" href="{% url 'quiz:index' %}">Index</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'quiz:startquiz' %}">Start Quiz</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'quiz:signup' %}">Sign Up</a></li>
                </ul>
            </div>
            {% include 'loginpartial.html' %}
        </nav>
        </div>
    </div>

    <div class="container body-content">
        {% block content %}

        {% endblock %}
        <hr />
        <footer>
            <p>&copy; {{ 2019 }} - Beyond Coaching. RN QuizMaster</p>
        </footer>
    </div>

    {% block scripts %}
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    
    <style>   
    </style>

    {% endblock %}
</body>

</html>

rn_quiz/homesite/templates/login.html
{% extends "base_site.html" %}
{% block content %}
<div class="card">
 <h5 class="card-header">Login</h5>
<div class="card-body">
<p class="card-text">
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}
<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>
</p>
</div></div>
{% endblock %}

rn_quiz/homesite/templates/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Welcome {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
</form>
{% else %}
<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>
{% endif %}